### PR TITLE
Pinybot beta Connected

### PR DESCRIPTION
**Pull request by CrookedTech**
ok i reuploaded the files since the previous one was uploaded the wrong way.

### CODE REVIEW

**Comment by Autotonic** [comment]
@CrookedTech Please learn git. When you delete and upload files it is very very hard to see what has changed. Git uses diffs for this reason.

**Comment by GoelBiju** [comment]
Great work @CrookedTech , I appreciate your help. I will merge the pull request to the new version, I cannot merge it straight away as there are changes currently made which hasn't been pushed onto the repository yet.

@Autotonic was just stating how using Git on your computer would help out pointing the differences you upload in files, compared to if you uploaded straight to GitHub. You can have a look at [this tutorial](http://product.hubspot.com/blog/git-and-github-tutorial-for-beginners) which when I searched quickly looks good at explaining about Git.

Thank you!

**Comment by CrookedTech** [comment]
@Autotonic yeah i know the reason why i uploaded from files is because i had trouble updating it
sorry, i did fixed that now you can see the differences.

@GoelBiju  thanks bro thats fine i just uploaded to speed the process i know it still needs to improve and the beta version is not finished yet i think in my opinion  instead of adding the autobans files in the rooms\someroom directory is better to  use the old way as a file directory called files i know the porpouse of that just to specify the config for each room, but just in my opinion i prefer it as a global configuration.

**Comment by GoelBiju** [comment]
I know what you mean there @CrookedTech , however this was how it was arranged in pinylib and the only issue would be how we would handle autobans in the event where we use the script in more than one room (how could we know which account/nickname to ban applies for which room if we used a global file)?

**Comment by CrookedTech** [comment]
@GoelBiju yeah  thats fine i didnt mean it, like the configuration was in the wrong directory, just giving a concept like most of us are used to the old configuration but is the same thing.
but the way it is, is just fine.

**Comment by GoelBiju** [comment]
Thanks for the suggestion anyway @CrookedTech , I have put in the new changes. Thank you for your help.

**Pull request closed without merging**
